// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ7hhEmvKhHLOZOhKaPxE-ds7aCaDjvpU',
    appId: '1:289441299689:android:091dfe6b194b9d36d84478',
    messagingSenderId: '289441299689',
    projectId: 'lanlan-app',
    storageBucket: 'lanlan-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ_7Tvrqr-xNGqTdmWyqxfcbaMF_CkRwI',
    appId: '1:289441299689:ios:969d0df6efa0cb87d84478',
    messagingSenderId: '289441299689',
    projectId: 'lanlan-app',
    storageBucket: 'lanlan-app.appspot.com',
    iosClientId: '289441299689-6c2cebhh1lb5c3hceu4d8lld736ot18e.apps.googleusercontent.com',
    iosBundleId: 'com.example.lanlanApp',
  );
}
